name: Make Artist Elements
description: File a request artist elements.
title: "[AristElements]: "
labels: ["Shader", "Model","Effect","Animation"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
    
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What Do You Want ?
      description: Also tell us, what do you want artist contents?
      placeholder: Tell us what you Want!
      value: "I want to make____."
          attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
 
